# Generated by Django 5.0.2 on 2024-03-08 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_movie_username_movie_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='username',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
