# Generated by Django 5.0.2 on 2024-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_remove_movie_username_movie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors_detail',
            field=models.ManyToManyField(default=None, related_name='hello', to='movie.actors'),
        ),
    ]
